### ISSUE TITLE
Improvment of case page (3 wishes)

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1691]
After a meeting here att CMMS, some wishes have come up for the case page:

- [ ] when we insert the OMIM number in the "diagnosis Phenotype" window or in the "Diagnosis gene" window, it would be nice to be able to write only the number not "OMIM:" has required at the moment.

- [ ]  it would be nice that, next to uploaded number, the OMIM text connected to the phenotype or gene appear, like for the HPO terms, in order to check we have typed the right numbers.

SEE attached file for schematic representation
[case page suggestions.pptx](https://github.com/Clinical-Genomics/scout/files/4166012/case.page.suggestions.pptx)

- [ ] we wish one more window entitled "HPO term for ClinVar" where we can collect the HPO terms for phenotype description for a patient that will be then uploaded in the ClinVar submission form. At the moment the HPO terms uploaded in the submisson form are the ones from the "Phenotypes groups" , these could be too general in some cases. Terms from both window should appear in the submission form if possible :)

**Comment by dnil** [comment]
Thanks! 1 and 2 would be what we refer to as Quality Of Life, but 3 sounds like a potential problem - or at least very reasonable request. The overall intention is that all HPO terms should be accessible for submissions to ClinVar, MatchMaker, Partial causatives etc. Presumably we just missed it there.

**Comment by moonso** [comment]
Hi, 

1. I think we reasoned that the diagnosis phenotypes could come from other sources than omim, such as [orphanet](https://www.orpha.net/consor/cgi-bin/index.php), when this was created. Since we do not use omim we could absolutely remove those extra letters.

1. This is also a good suggestion that is easy to implement

1. Could we you give an option to check the ones that should be included from the total list of phenotypes @northwestwitch ?

**Comment by northwestwitch** [comment]
Working on this now. Was there any reason why OMIM terms should be provided entire by the user and we didn't implement the autocompletion (suggesting diagnoses when you type the first 3 OMIM numbers or so), as for HPO terms? Because I could fix that!

**Comment by dnil** [comment]
I think not, so sounds excellent - but ping back at @4WGH. We don't use the diagnosis terms so much..

**Comment by northwestwitch** [comment]
> We don't use the diagnosis terms so much

Maybe this way we will use them more! :)

**Comment by dnil** [comment]
It sort of routes back to the way we use these in answers. 

When there is only one possible diagnosis associated with a gene, this becomes a trivial mapping and filling it in will be seen as unneeded and just red tape. 

When there are multiple possible diagnoses associated with a gene (marked as causative), it is sometimes possible to pick one based on some distinguishing feature, but more often than not the different disorders are part of a fairly gradual spectrum, and the reply becomes that the mutation explains a range of disorders. It certainly doesn't hurt to have it there, but I doubt this will be a blockbuster feature. 😉

**Comment by 4WGH** [comment]
the reason to fill the diagniosis number is connected to CLinVar submission. Once we start with that (hopefylly soon) then it will be bery muchused :)

**Comment by northwestwitch** [comment]
Providing precise diagnoses is good also when you share cases on matchmaker, let's do it!

**Comment by northwestwitch** [comment]
What is the functional difference of providing either OMIM diagnosis phenotypes or OMIM diagnosis genes?

![image](https://user-images.githubusercontent.com/28093618/74329670-87f79300-4d90-11ea-991a-aa8859c8d8c8.png)

**Comment by northwestwitch** [comment]
I've fixed the first 2 wishes in this #1707, which will make it easier to handle OMIM diagnoses (including assignment and gene visualization).

Regarding the 3rd wish I've been testing what is already in place. It looks like that everything is included in `Added phenotypes` (bottom right), that comes both from `Phenotype groups` and `Diagnosis phenotypes` 

![image](https://user-images.githubusercontent.com/28093618/74521275-7261a500-4f19-11ea-8e5c-9002af67594e.png)

is already included as HPO options in the clinvar form, not just phenotype groups.
![image](https://user-images.githubusercontent.com/28093618/74521425-accb4200-4f19-11ea-85ee-8fd57c4e7e77.png)

Regarding your request of including yet another category of HPO terms (just those to be included in clinvar) I'm a bit doubtful, because this would create confusion especially for those users which don't use the clinvar submission form. 
As the things are now it is quite easy to add and remove an HPO term to a case, so if for instance you'd like to save the clinvar form for a case with slightly different phenotypes than you have, you could modify the HPO terms of it before the clinvar export and then revert to the original phenotypes when you are done. The HPO terms saved in the clinvar form will be not overwritten if you modify the case after.

**Comment by 4WGH** [comment]
![bild](https://user-images.githubusercontent.com/12525201/77521207-97372980-6e82-11ea-8a53-dd58eca5a440.png)

disease appearing :)
gene symbol still missing :(
