### ISSUE TITLE
"Filter and export" excludes most information for variants that overlap multiple genes

### ISSUE THREAD

**Issue by bjhall** [Clinical-Genomics/scout#2429]
When a variant overlaps more than one gene, like this:

![bild](https://user-images.githubusercontent.com/11991860/110593844-60821e00-817c-11eb-8da4-6134e55c8b34.png)

The row in the export csv is almost empty

![bild](https://user-images.githubusercontent.com/11991860/110593796-52cc9880-817c-11eb-9002-ded73012eae4.png)

A quick look at the code suggests that this should work, but I haven't debugged it yet. I'll try to find some time later today.

**Comment by northwestwitch** [comment]
Hi @bjhall, while I was working on #2434 I've realized that transcript collection pior to variant export had the same old problem of not taking into account genome builds (it was defaulting to build 37). Perhaps this issue is fixed by that PR, (or perhaps not? ). Would you like to test it?

**Comment by bjhall** [comment]
I'm at 0a30d0ea9cc89c1643531dbc6740090f8c40015f and I'm still getting empty fields for variants overlapping multiple genes. I'll try to debug it now and get back to you! Are you not seeing the same?

The primary transcript selection looks good though! :)

**Comment by northwestwitch** [comment]
Thanks for testing! I see variants with multiple genes correctly, at least in all cases I've tried, that's why I assumed it might be related with the genome build..

**Comment by bjhall** [comment]
OMG I'm so embarrassed... This is not a bug in Scout but in my usage of Excel! When I open the file in Excel it automatically splits on semi-colons, then when I manually split the data on commas it will overwrite these columns (Excel even gave me a warning that I ignored).

Maybe it should use some other separator just to accomodate fools like me?

I'll close this issue immediately and never use Excel again...

**Comment by northwestwitch** [comment]
> I'll close this issue immediately and never use Excel again...

Hahaha no worries, Excel fools everyone one day or another 😄 
But we could actually use another separator, do you have any preference?

**Comment by bjhall** [comment]
Maybe `&`? 

`,` and `|`are already used right?

**Comment by northwestwitch** [comment]
What about " - " ?

**Comment by bjhall** [comment]
That's fine with me!
