### ISSUE TITLE
How does Scout calculate or show VAF/AF? Probably incorrect AF is show on a case

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#2920]
The variant https://scout.scilifelab.se/cust087/F0041488-2/cancer/31241819ff9fff9273bc6c4e34aa0ccb?cancer=yes shows an AF of 0.4889:

![image](https://user-images.githubusercontent.com/1086877/137111279-0ec91b51-062d-48fb-a5e3-7c5d4ae16122.png)

Is VAF recalculated on Scout? When I look at the case `cleanasp` on Hasta, VAF is set at 0.375

`X	100611164	.	C	T	284	PASS	SAMPLE=cleanasp;TYPE=SNV;DP=703;VD=264;AF=0.3755` 

Does Scout recalculate VAFs? Where does `0.4889` come from? Or am I looking at wrong case?

**Comment by northwestwitch** [comment]
Tested installing Scout with an up-to-date version of cyvcf2 (0.30.11). The problem persists

**Comment by mathiasbio** [comment]
We see this issue still in how Scout recalculates the VAF for variants, and which for the majority of variants is probably not an issue, but when there are regions with multiple overlapping variants and few reference reads it can have quite dramatic misleading effects on the VAF. 

We see in the case: sureroughy uploaded to Scout stage for cust087 this variant for instance

<img width="525" alt="image" src="https://github.com/user-attachments/assets/192be0ec-4b76-4a00-a747-bf368af3a92c">

But where in the VCF it has these values:

| GT  | DP   | VD  | AD      | AF     | RD      | ALD     |
|-----|------|-----|---------|--------|---------|---------|
| 0/1 | 1863 | 417 | 230,417 | 0.2238 | 109,121 | 222,195 |

It seems then that the function that Scout uses to calculate the VAF is based on VD / sum(AD), instead of VarDict which calculates AF with VD / DP which also seems to be in pretty good agreement with bamfile in IGV:

<img width="918" alt="image" src="https://github.com/user-attachments/assets/1f5d48ce-e4a4-4ffe-801c-2a46e2393d3a">

I think in general that the better approach is to calculate the VAF based on VD / DP though I honestly don't know in this case how VarDict determines what reads are alternative and which ones are supporting the reference, and if maybe some of the "missing" AD counts may not be simply reads that actually support the variant but which the variant caller didn't know how to interpret... but regardless it seems to me to be better to use the VD / DP formula, or to simply take it out of the hands of Scout and just pick up the AF values from the info-field (which are present for both TNscope and VarDict)

**Comment by dnil** [comment]
First, good to hear that triallelic calling is now fixed! That means this is on the table. We are not aware of any issues with cyvcf2 and biallelic variants.

Using the caller AF with a fallback of VD / DP seems like a very straightforward solution (would already happen if the ref- and alt depths was `-1`/unset). Let's just make sure we are getting this right. I have a fairly strong hunch this should be caller specific, but we could make that e.g. for TNScope and VarDict if they are similar here.

Are the VAF and DP-counts from VarDict now correct, or at least the best we have? If I recall correctly, we used to have a large variance on the DP, stemming from different read quality filtering etc, with the ref and alt depths being more reliable, assuming one corrects them properly when splitting/normalising multiallelics. This would be comparable to the GATK situation. Seeing the REF count shift so wildly on this variant between different versions, it is fair to say this is not the situation here. 😊

Of more general interest, an indel of 175 is pretty large. This is something that really is borderline SV, but if VarDict says it found it using in-read info even after splitting out SVs to another file, then I guess we will have to buy it, although it seems more like a DUP slightly longer than read length. No INS has been marked in the alignment either? Looks like the call would be improved using split read and coverage information.

**Comment by mathiasbio** [comment]
Sorry I forgot to check up on this issue. But very relevant concerns raised, and I haven't verified that either TNscope or VarDict are counting DP and AF values in unexpected ways. I wouldn't be surprised! 

I have seen previously, years ago, that the values from TNscope have been a bit strange which were either due to low quality reads, or how it does some local assembly of reads before doing variant-calling. I have even seen variants with read-support of 0, but this was back in 2020 or something and maybe things have changed. (and either way VD / DP in that case wouldn't be very good either)

But in general when I have looked at the same variant called by both callers, the AF has tended to agree quite well at least between TNscope and VarDict, and I haven't seen any inconsistent variants so far. I think it makes sense to trust the callers AF values for now and if we receive any reports about strange AF values we can explore this further?

**Comment by mathiasbio** [comment]
Regarding the InDel it's still an issue in VarDict that we haven't taken out the SV variants and merged them with the other SV-calls. Let's try to fix this for the next release of balsamic...I think the clinicians are starting to become more ok with looking for these FLT3 variants in the SV view instead
