### ISSUE TITLE
Weird sorting of STRs first 2 times that the page loads

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#5586]
To reproduce:
 
1. Go to a nallo case (build 38)
2. Go to STRs
3. Notice that some gene names are even missing 
4. Reload, notice that the sorting is messy
5. Reload and all is good, and sorting is fine

**Comment by northwestwitch** [comment]
Also, lines with missing genes: https://scout38-stage.sys.scilifelab.se/cust002/2025-10053-03-case/str/variants, deselect the OMIM panel

**Comment by northwestwitch** [comment]
> Also, lines with missing genes: https://scout38-stage.sys.scilifelab.se/cust002/2025-10053-03-case/str/variants, deselect the OMIM panel

This specific thing was fixed by #5587

**Comment by dnil** [comment]
Hm, didn't we close this?

**Comment by northwestwitch** [comment]
> Hm, didn't we close this?

The problem was fixed after visiting the page again but we never understood why if I remember correctly

**Comment by fellen31** [comment]
Not sure exactly which version is in stage atm, but still an issue there.

1st refresh:
<img width="328" height="426" alt="Image" src="https://github.com/user-attachments/assets/51d9f679-bf32-4842-9f27-61f7d6e802cb" />

2nd refresh:
<img width="323" height="418" alt="Image" src="https://github.com/user-attachments/assets/a416e01d-356b-4324-88d6-f6a969152525" />

3rd refresh:
<img width="328" height="418" alt="Image" src="https://github.com/user-attachments/assets/aaf52b9f-a249-4c28-8885-9ca3ba1f8a29" />

4th refresh:
<img width="331" height="393" alt="Image" src="https://github.com/user-attachments/assets/63597dd6-a9f8-4346-ae9a-37e3564b2cb3" />

finally, 5th refresh:
<img width="329" height="406" alt="Image" src="https://github.com/user-attachments/assets/a2ce31c1-49bb-44de-9a61-44c12c79fb94" />

**Comment by fellen31** [comment]
I think (at least some of) this issue is still persisting with 4.104.0. Could you have a look at any of the control-nallo* cases in https://scout38-stage.sys.scilifelab.se/cust002/cases?

**Comment by northwestwitch** [comment]
Oh no, we'll check!

**Comment by dnil** [comment]
And they are freshly re-uploaded? The issue is only partly resolved for old cases.

**Comment by dnil** [comment]
Looks like it!

**Comment by fellen31** [comment]
> And they are freshly re-uploaded? The issue is only partly resolved for old cases.

Ah alright, didn't understand that. At least the top 5 cases should have been uploaded after 17 yesterday, I didn't check the version then...I'll reupload one case to cust000 for good measure.

**Comment by dnil** [comment]
Nono, my bad - we didn't do the load parsing part yet! That was just wishful thinking. It's still open boxes in https://github.com/Clinical-Genomics/scout/pull/5634; we were meaning to add an issue for it.

**Comment by fellen31** [comment]
Alright. Well it's better than before, so thanks for that! I'll leave it to you whether to leave this issue open, or open another.
